### ISSUE TITLE
TestExternalFiles - no report output from double-click on script Windows 10

### ISSUE THREAD

**Issue by ve3meo** [ricko2001/Genealogy-scripts#4]
Now that I've got the script running reliably from the IDLE Python shell (?), I'm puzzled as to why double-clicking the .py script from Windows File Manager elicits the black Python window briefly as expected but outputs nothing to the txt file. Until now, I had attributed it to execution stopping on an error before outputting but that cannot be the case now.

**Comment by ve3meo** [comment]
1.2.0.0 does not output the report when run by double-clicking the .py script but the .exe (which I've just discovered - low on the github learning curve!) does. The python window is more informative than before and gives this error report:
`ERROR: The ini configuration file, RM-Python-config.ini must be in the current directory.` 
Thing is, it is in the same directory as the .py and .exe files. It's as though executing the script via Windows file association is changing the current directory to somewhere else. I tried putting the ini file into the Python program folder but, because that was from the Windows Store, the security barriers were more than I could overcome.

**Comment by ve3meo** [comment]
Tried the shortcut yesterday w/o success. Tried again today with 1.2; same. 

The cmd file works.

Found that launching by double-click results in "C:\WINDOWS\system32" for the current working directory... and just see your find which I will try next.

**Comment by ve3meo** [comment]
Eureka!
32 IniFile=sys.path[0] + "\RM-Python-config.ini"
That works!

**Comment by ve3meo** [comment]
So sys.path[0] value should be used in any script file that wants to be used to invoke the python interpreter AND wants to read or write other files that are located relative to the script? And that's the same for both the MS Store Python and the install from python.org.

**Comment by ricko2001** [comment]
It looks like I was about half an hour behind you...
I installed the MS Store version on a laptop and got the same results you did.
I'm surprised the shortcut method didn't work.
Anyway- pretty sure that the difference is in how python is started: python.exe vs. py.exe (the python launcher installed by the python.org installer)

I'll add that line of code and make a 1.2.1 release so nobody else has to go thru the torture you did.
Thanks very much.

**Comment by ve3meo** [comment]
Maybe a half-hour behind on that issue but a light-year ahead overall!

Just checked 1.2.1 and both launching the .py script and the .exe app from the Windows File Manager work. The latter gets checked by Windows Defender which one has to assure that the app is okay to run, the first time.
